let isLocation = false;
let lang = navigator.language;
let searchCity = document.querySelector("#search");
let find = document.querySelector("#find");
let currentCity = document.querySelector("#current-city span:first-child");
let currentCountry = document.querySelector("#current-city span:last-child");
let currentTime = document.querySelector("#current-time");
let currentImg = document.querySelector("#current-img");
let currentTemp = document.querySelector("#temp");
let currentTemperatureInfo = document.querySelector("#temp-info");
let currentSunrise = document.querySelector("#sunrise");
let currentSunset = document.querySelector("#sunset");
let currentMaxTemp = document.querySelector("#max-temp");
let currentMinTemp = document.querySelector("#min-temp");
let currentWind = document.querySelector("#wind span:first-child");
let currentHumidity = document.querySelector("#humidity span:first-child");
let forecastHourlyContainer = document.querySelector(".hourly");
let forecastDailyContainer = document.querySelector(".daily");
let latitude;
let longitude;
